services:
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - path: .env
volumes:
  pgdata:
  # api:
  #   image: the-writers
  #   build:
  #     context: .
  #   ports:
  #     - "5432:5432"
  #   depends_on:
  #     - database
