-- AlterTable
ALTER TABLE "Writer" ADD COLUMN     "birthDate" TIMESTAMP(3),
ADD COLUMN     "country" VARCHAR(100),
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "popularBook" VARCHAR(100),
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
